# Generated by Django 5.0 on 2024-01-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_is_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="close_date",
            field=models.DateField(),
        ),
    ]
