# Generated by Django 5.0 on 2024-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
