startproject:
	python django/manage.py startproject settings

runserver:
	python django/manage.py runserver

startapp:
	python django/manage.py startapp tasks

makemigrations:
	python django/manage.py makemigrations
	
migrate:
	python django/manage.py migrate

createsuperuser:
	python django/manage.py createsuperuser

createadmin:
	python django/manage.py createadmin

format:
	black ./

test:
	python django/manage.py test django/