version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    expose:
      - 5000
    volumes:
      - ./src/templates:/app/templates
      - ./src/static:/app/static
      - static_volume:/app/static
    depends_on:
      pg:
        condition: service_healthy

  nginx:
      build: ./nginx
      ports:
        - 8080:80
      depends_on:
        - app
      volumes:
        - static_volume:/app/static

  pg:
    image: postgres
    environment:
      POSTGRES_DB: diary
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d diary -U username"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg-data:
  static_volume: