# Generated by Django 5.0 on 2024-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
