# Generated by Django 5.0 on 2024-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="close_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
