# Generated by Django 5.0 on 2024-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_close_date_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
